### PR TITLE
Update EliteAPI.

### PR DESCRIPTION
**Pull request by laramiel**
* Add fields from 3.4
* Change journal handling to use a file watcher, which should reduce the latency.
* update some deprecated names.

It's been a while since I did any C#, so please look this over carefully and take what works. Note: The Task.Run() is probably no longer necessary, but it's not entirely clear what it as there for in the first place.

### CODE REVIEW

**Comment by Somfic** [comment]
Hi laramiel, thank you for the pull request!

Would you be able to change the target branch from `master` to `dev` please?

Thank you!

**Comment by laramiel** [comment]
Sure. I didn't realize that you had a dev branch until after this pull request.

**Comment by laramiel** [comment]
Quite a few conflicts. I'm abandoning this and will send a new one.

**Comment by laramiel** [comment]
Quite a few conflicts, abandoning.

**Pull request closed without merging**
